### ISSUE TITLE
Improve Metrics names

### ISSUE THREAD

**Issue by garrensmith** [prisma/client-planning#66]
The metric names are a little confusing. I would like to go through them and improve the names of the metrics so that it is more obvious what they are collecting.

**Comment by matthewmueller** [comment]
Docs: https://www.prisma.io/docs/concepts/components/prisma-client/metrics

**Comment by matthewmueller** [comment]
Just went through without looking at docs and tried to right what I think each one does below:

- query_total_queries: total number of prisma client queries (e.g. select) since connecting
- query_total_operations: total number of prisma client operations (e.g. findMany) since connecting
- pool_active_connections: number of connections to the database that are actively executing a query
- pool_idle_connections: number of connections to the database that are ready to execute a query
- pool_wait_count: number of queries waiting for an active connection to execute a query
- query_active_transactions: number of open transactions for a given query. Can be one or zero.
- pool_wait_duration_ms: Number of milliseconds the average query needs to wait to get an active connection.
- query_total_elapsed_time_ms: Total number of milliseconds spent waiting to get an active connection.
- query_operation_total_elapsed_time_ms: Total number of milliseconds spend executing all queries.

Two thoughts: 
- Could be nice to know the unit on each of them without looking it up, if they're averages (avg_*, counts (num_*).
- Counterpoint: Hard to make them more obvious without making them more verbose. I don't think we need to expect that every stat should be immediately intuitive.

**Comment by garrensmith** [comment]
After a bit of research and planning. We want to rename the metrics as follows:

 Original  | New Name | Description |
| --- | --- | ---  |
| query_total_queries  | prisma_datasource_queries_total | Total number of Datasource Queries executed |
| query_total_operations  | prisma_client_queries_total  | Total number of Prisma Client queries executed |
| query_active_transactions | prisma_client_queries_active | Number of currently active Prisma Client queries |
| pool_wait_count | prisma_client_queries_wait | Number of Prisma Client queries currently waiting for a connection |
| query_total_elapsed_time_ms | prisma_datasource_queries_duration_histogram_ms | Histogram of the duration of all executed Datasource Queries in ms |
| query_operation_total_elapsed_time_ms | prisma_client_queries_duration_histogram_ms | Histogram of the duration of all executed Prisma Client queries in ms |  |
| (new) | prisma_pool_connections_opened_total | Total number of Pool Connections opened |
| (new) | prisma_pool_connections_closed_total | Total number of Pool Connections closed |
| (new) | prisma_pool_connections_open | Number of currently open Pool Connections |
| pool_active_connections | prisma_pool_connections_busy | Number of currently busy Pool Connections (executing a datasource query) |
| pool_idle_connections | prisma_pool_connections_idle | Number of currently unused Pool Connections (waiting for the next datasource query to run) |
| pool_wait_duration_ms | prisma_client_queries_wait_histogram_ms | Histogram of the wait time of all Prisma Client Queries in ms |

The naming convention is described here https://www.notion.so/prismaio/Metrics-Naming-Convention-d00b410e56c04b85bd95e72d0b306161

**Comment by dpetrick** [comment]
How would metrics work in a multi-datasource environment? Pools will be separated and metrics like `prisma_datasource_queries_total` will be tied to their individual connectors most likely. I guess there's a dimension added in the metrics name down the line? Should we already consider this?

**Comment by garrensmith** [comment]
That is a little tricky to answer right now since I don't know a lot about the multiple data source work. 
I think we should probably change the metrics method to be something like this:
```
let metricsSource1 = await client.$metrics.prometheus("datasource_1");
```
And if no source was entered we would supply an array with the metrics for all the different datasources

**Comment by andrew-walford-prisma** [comment]
Will this be a breaking change?

**Comment by garrensmith** [comment]
Its still a preview feature so it won't be a breaking change.
